### PR TITLE
Dont include relationship if data is null

### PR DESCRIPTION
**Pull request by sebreh**
According to the JSONAPI spec, the `data` part of the attribute should be null for empty one-to-one relationships, not the entire relationship.

http://jsonapi.org/format/#document-resource-object-related-resource-links

### CODE REVIEW

**Comment by freeall** [comment]
Hey @sebreh :)

I wanted to transfer the repo to you or peakon, but I can't since you and peakon both have forks of it. Can you remove your fork and I'll transfer it to you?

**Comment by sebreh** [comment]
@freeall cool! I've removed the fork repo now.

**Comment by sebreh** [comment]
@freeall just let me know here when you've transferred it.

**Comment by freeall** [comment]
@sebreh Tried to transfer to peakon but it says I don't have admin rights. Then I tried to transfer to you, but it says you have a fork. Can you remove that and I'll try to transfer to you.

**Comment by sebreh** [comment]
@freeall Deleted my fork now, sorry about the delay. Can you try transfering it again?

**Comment by freeall** [comment]
@sebreh done. You should have a notification/email from github now

**Comment by sebreh** [comment]
cool, thanks.

**Comment by sebreh** [comment]
@freeall ah, could you transfer the npm module ownership too? :) https://docs.npmjs.com/cli/owner

**Comment by sebreh** [comment]
NPM user is `sebreh`

**Pull request merged**
